[package]
name = "beacon"
version = "0.1.0"
edition = "2021"

[dependencies]
commons = { path = "../commons" }
libp2p = { version = "0.43.0", features = ["tcp-tokio"] }
serde = "1.0.136"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros", "io-std"] }